### ISSUE TITLE
Permission to port back refactorings to jobackman/SpellNotifications

### ISSUE THREAD

**Issue by jobackman** [oscarwika/SpellNotifications#5]
Hi @oscarwika,

Tonight I decided to get off my ass and spend some of my evening testing and updating [SpellNotifications] to make it TBC/Classic compatible. As I was finishing up and I was doublechecking that it deployed correctly I happened to come across your fork! 

It looks like I was a few hours behind you 😅 

![image](https://user-images.githubusercontent.com/732505/119411394-a74ad300-bcea-11eb-9a93-486501fb9bef.png)

I have to say that I love the refactoring that you've done, it makes the addon a lot easier to follow along and maintain. 
I especially love the bits you did with the schools, colors and miss types. It helps the readability a ton! 

---

_**I thought I would open this ticket to ask you if you are okay with me porting these refactorings back to the [main repo]?**_ 

I dont want to plagiarize your good work, but I would love to have it in the main repo! Though I would probably also keep the stuff that is missing in your addon so that I dont lose functionality i.e. reflects, groundings, immunes etc. 

---

I was also wondering what your vision is for your fork? 
- I take it you're planning on having a TBC version of it. Is it only for tbc or other wow versions too? 
- Do you mean to have it as your own _"flavor"_ of SpellNotifications, or did you make this fork just to get it working for TBC? 
- Any plans of other new features that werent in any of the other implementations? 

My own idea of what I want it to be is something along:
- Keep it simple.
- Generic use addon that announces hard-to-tell combat events without any big configuration fuss. Not specifically tailored to one class/spec/person or another. 
- Should work across classic/tbc/retail
- No specific plans of new features that I can think of. I'm open for discussion, but I haven't felt the need for it to do more so I've just been maintaining it. Making sure that it works. 
- Regarding sounds; I never used the original version by Veev so I don't know what I missed out here and I cant say that I felt the lack of them. Then again I'm not opposed to sounds triggering on certain important enough events

If we both feel that our visions align I dont see any reason not to work together. Perhaps keeping it to a single repo for all the wow clients? Since I dont actively develop the addon a lot I wouldnt mind adding you as a maintainer if you're interested and we align vision-wise😄 

Tonight I spent some time updating my repo so that it can better handle all the different wow clients these days. Now with [Bigwigs Packager] and github actions it'll automatically deploy a new versioned tag to all wow clients. With the bigwigs packager it also allows me to code-split if there is a need to keep some things separate between the wow versions.

The day after tomorrow I think I'll spend some time after work porting your refactorings back to my repo (_if you're okay with it_). 
From there we could talk about how to continue, if you're interested

_Cheers_

[SpellNotifications]: https://www.curseforge.com/wow/addons/spellnotifications
[Bigwigs Packager]: https://github.com/BigWigsMods/packager
[main repo]: https://github.com/jobackman/SpellNotifications

**Comment by oscarwika** [comment]
Hi @jobackman, nice to meet you! 😄

Thank you for the compliments, I appreciate it!

I've always had a private version of this addon that I would manually zip and send to my friends/arena team ever since i first downloaded it in Mists of Pandaria. It included a lot of personalized notifications and sound warnings, so I never thought about sharing it with the public.

---

_To your question on using my refactoring:_

Thank you for asking, feel free to use it any way you like! 👍🏼 

---

_Vision for the fork:_
- Initially I thought, "okay, I can fork this project and suggest my refactoring", but then I remembered yours was for retail and mine was for TBC. Then I thought to myself, "well that doesn't really make sense, suggestion something that might not work on retail".
- So, then I deleted the fork shortly after and started figuring out what I could do to make a general solution that would work on all versions of the game.
- Then I realized they probably use the same API, so I just added two new lines in the .toc file, tested the different events worked as expected and pushed the changes.

In hindsight I could've/should've just proceeded with the fork. 💭 

---

_Plans for new features (if any):_

Some features I was thinking about was just some simple slash commands to enable/disable sound (if I add more of those) and/or give the user the option to change color on the notification message. 

---

_What the addon should be_
I agree on all the points you have about what the addon should be!

_Regarding sound_
The sounds were something I played around with a lot, but I don't think they(all the sounds Veev had implemented) should be used in a general solution. Some of them might be nice to have, so that's why I've been thinking about adding those slash command. 
Also, there are already addons that do this, so that's also a reason not to have it.
- Sounds proved to be very effective in high-end arena in situations where you quickly needed to react to some cooldown used by the enemy. So if there was an ability we wanted to get notified about, I'd just add a new function and a new sound file.
- Most of the sounds are just short snippets, so when you would hear a "thud" sound for example you would instantly know that the target was immune to your ability or whatever.

---

_Final thoughts_
It seems like we have the same vision for what the addon should be. 

So go ahead and implement the refactoring I've done so far. If you add me as a maintainer I can commit the refactoring I've done to "reflects, groundings, immunes etc." (MissTypes.lua will be used for some of this). I have a working version locally, I just want to test it more on the different versions of the game before i commit it.

I will have to take a closer look at that Bigwigs Packager, but that sounds very neat! 😄 

Best regards,
Oscar

P.S.
I had a pouding headache when i wrote this and it's almsot 4am, so I hope everything made sense. 🔨 

Also, in order to make it easier for the user I will call my project on Github/CurseForge something entirely different, so that users looking for the original simple addon always know where to find it. Then if I do put my own flavor to it, my friends/arena mates or whatever can go get that personalized version somewhere else. 💯

**Comment by oscarwika** [comment]
I thought about it more and I think I will just delete this project and the project on CurseForge, given that we now work together on a general solution.

I made a PR with some changes that hadn't been pushed to github yet.

**Comment by oscarwika** [comment]
Maybe we can move this issue to your repo somehow? I can only move it to my own repos it seems, so maybe I need some kind of access to do so?

**Comment by jobackman** [comment]
True enough, I'll invite you!

**Comment by jobackman** [comment]
Sent you an invite. Check afterwards if perhaps you can transfer this to the other repo

**Comment by oscarwika** [comment]
Didn't notice your message here!

I googled a bit and it seems like you can only move issues between repositories owned by the same user or organization, but it's whatever, not that important! 😄
